### ISSUE TITLE
[Feature] Progress Bar for Achievements

### ISSUE THREAD

**Issue by silvanheller** [s3inlc/cineast-evaluator#10]
There is currently no way to see your progress for most achievements. If you can, it is hidden under the profile page / the total score leaderboard.
Something like 'You only need to answer n more questions for your next achievement' or 'play 3 more games in a row to get 5% bonus score' would then be a natural followup at the end of a session.

**Comment by s3inlc** [comment]
Achievements are now displayed with a percentage how much it is completed as long as it isn't reached yet.

For achievements which can get reseted when the row gets interrupted, they will state the maximum which was reached until you have a new row which is bigger
