### ISSUE TITLE
[Feature] Reduce session length for unregistered users

### ISSUE THREAD

**Issue by silvanheller** [s3inlc/cineast-evaluator#5]
Currently, the session length is very long for the first game. Reducing the session length for unregistered users would allow for more instant feedback and motivate them to log in and play another game.

**Comment by s3inlc** [comment]
What would you regard as optimal session length for unregistered users to start?

**Comment by silvanheller** [comment]
Somewhere between 10 and 20? If you're calculating 5 second per answer, 20 questions gives you a session length of approx. 2 minutes which should be ok

**Comment by lucaro** [comment]
I think 5 seconds it too high an estimate. Starting with 20 questions sounds reasonable.
