### ISSUE TITLE
Share links

### ISSUE THREAD

**Issue by lucaro** [s3inlc/cineast-evaluator#8]
The Share on Facebook button is currently broken and the Share on Twitter button produces a tweet which only contains the link to score.php without the parameter or any text. (The twitter problem might be on my end due to privacy badger...)

**Comment by s3inlc** [comment]
Facebook is currently broken, that's correct. That your Twitter share is not correct makes no sense, perhaps you're right with your idea about the privacy settings.

When I share on Twitter I get such a text:
```
I just scored 144'311 points on @ArtSimily 
https://artsimily.com/score.php?game=647&affiliate=9qbq3NkRj5 #artsimily
```

**Comment by lucaro** [comment]
This is what it looks like on my end:
![grafik](https://cloud.githubusercontent.com/assets/246519/26591932/7f9594d2-455f-11e7-8b7e-e4b3dd2086cd.png)

**Comment by s3inlc** [comment]
Can you give me what is exactly provided as link when you copy the link of the share button?

**Comment by lucaro** [comment]
Sure, but I don't think there's much you can do about this...

`<img src="moz-extension://c72ad565-9048-4c1c-95fc-5ef4695f7342/skin/socialwidgets/Twitter.svg" class="privacyBadgerReplacementButton" title="PrivacyBadger has replaced this Twitter button.">`

**Comment by s3inlc** [comment]
As I see on your other screenshot I'm pretty sure that this problem is related to your plugin which causes the button also to look completely different than the Facebook button and very likely messes up the link then.

So I recommend that you turn of the plugin on artsimily.com and it should work without any problems.
